language: csharp
solution: SharpStar.sln
mono:
- latest
addons:
  apt:
    packages:
    - p7zip-full
script:
- xbuild /p:Configuration=Release SharpStar.Mono.sln
before_deploy:
- mv Lib/* SharpStar/bin/Release
- mv linux/* SharpStar/bin/Release
- mono SharpStar/bin/Release/MkBundleHelper.exe SharpStar/bin/Release/ SharpStar.exe
- bash SharpStar/bin/Release/mkbundle.txt
- rm SharpStar/bin/Release/MkBundleHelper.exe
- rm SharpStar/bin/Release/mkbundle.txt
- 7z a Star.zip ./SharpStar/bin/Release/*
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIZ43C6YADAB5SSZA
  secret_access_key:
    secure: HFfgyVBi6oNSiT9JN4nJUm2HHOSpbjiEQPRbO+UNzKjS0Wfwd9vXHHprNvdutHtJBJgj4wPytUupE0//VukUdGeAmzpTRJbk3p6lCgK8MZqAn73PUZ87KOF6Trl7W9bdlj+oVNgBVwXxwmHY0vkvppTdwAdrXrtLRBkWMOGjXsg=
  bucket: starbound-star
  local-dir: /home/travis/build/SharpStar/Star/SharpStar/bin/Release
  upload-dir: linux
  acl: public_read
  on:
    repo: SharpStar/Star